// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate(arg1) {
  return window['go']['main']['App']['CheckUpdate'](arg1);
}

export function GetProcessIcon(arg1, arg2) {
  return window['go']['main']['App']['GetProcessIcon'](arg1, arg2);
}

export function GetProcesses() {
  return window['go']['main']['App']['GetProcesses']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function OpenReleasePage(arg1) {
  return window['go']['main']['App']['OpenReleasePage'](arg1);
}

export function SkipVersion(arg1) {
  return window['go']['main']['App']['SkipVersion'](arg1);
}

export function TerminateProcess(arg1, arg2) {
  return window['go']['main']['App']['TerminateProcess'](arg1, arg2);
}
