// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {update} from '../models';
import {process} from '../models';

export function CheckUpdate(arg1:boolean):Promise<update.Result>;

export function GetProcessIcon(arg1:number,arg2:number):Promise<string>;

export function GetProcesses():Promise<process.ProcessSnapshot>;

export function GetVersion():Promise<string>;

export function OpenReleasePage(arg1:string):Promise<void>;

export function SkipVersion(arg1:string):Promise<void>;

export function TerminateProcess(arg1:number,arg2:number):Promise<void>;
